# Generated by Django 3.0.6 on 2020-05-18 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_auto_20200517_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Время комментария'),
        ),
    ]
