# Generated by Django 3.0.6 on 2020-05-18 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_auto_20200518_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Время комментария'),
        ),
    ]
