# Generated by Django 3.0.6 on 2020-05-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_auto_20200518_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
