# Generated by Django 3.0.6 on 2020-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0017_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=1, max_length=40, verbose_name='имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
