# Generated by Django 3.0.6 on 2020-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_auto_20200519_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(verbose_name='дата публикации'),
        ),
    ]
